# Generated by Django 5.0 on 2023-12-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_22', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmanager',
            name='profile_pic',
        ),
    ]
