# Generated by Django 5.0 on 2024-01-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_22', '0008_alter_appointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('two wheeler with gear', 'two wheeler with gear'), ('two wheeler without gear', 'two wheeler without gear')], max_length=50)),
                ('vehicle_no', models.PositiveIntegerField()),
                ('vehicle_name', models.CharField(max_length=40)),
                ('vehicle_model', models.CharField(max_length=40)),
                ('vehicle_brand', models.CharField(max_length=40)),
                ('problem_description', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('cost', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('Repairing', 'Repairing'), ('Repairing done', 'Repairing done'), ('Released', 'Released')], default='pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App_22.customer')),
                ('workmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App_22.workmanager')),
            ],
        ),
    ]
