# Generated by Django 5.0 on 2024-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_22', '0009_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmanager',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
