from django.urls import path

from App_22 import views, adminviews, customerviews, workmanagerviews

urlpatterns = [
    path('',views.demo,name='demo'),
    path('demo1',views.demo1,name='demo1'),
    path('demo2',views.demo2,name='demo2'),
    path('base1',views.base1,name='base1'),
    path('base2',views.base2,name='base2'),
    path('base3',views.base3,name='base3'),
    path('work',views.work,name='work'),
    path('customerdata',views.customerdata,name='customerdata'),
    path('note',views.note,name='note'),
    path('delete/<int:id>/', adminviews.delete, name='delete'),
    path('viewA',adminviews.viewA,name='viewA'),
    path('viewC',customerviews.viewC,name='viewC'),
    path('viewW',workmanagerviews.viewW,name='viewW'),
    path('login_view',views.login_view,name='login_view'),
    path('view_data',adminviews.view_data,name='view_data'),
    path('delete_data/<int:id>/', adminviews.delete_data, name='delete_data'),
    path('view_manager',adminviews.view_manager,name='view_manager'),
    path('delete_manager/<int:id>/', adminviews.delete_manager, name='delete_manager'),
    path('update/<int:id>/',adminviews.update, name='update'),
    path('feedback',customerviews.feedback,name='feedback'),
    path('feedback_view',adminviews.feedback_view,name='feedback_view'),
    path('reply/<int:id>/',adminviews.reply,name='reply'),
    path('viewreply',customerviews.viewreply,name='viewreply'),
    path('schedule',adminviews.schedule,name='schedule'),
    path('viewschedule',customerviews.viewschedule,name='viewschedule'),
    path('admin_view',adminviews.admin_view,name='admin_view'),
    path('delete_schedule/<int:id>/', adminviews.delete_schedule, name='delete_schedule'),
    path('appointment/<int:id>/',customerviews.appointment,name='appointment'),
    path('appointment_view',adminviews.appointment_view,name='appointment_view'),
    path('accept/<int:id>/',adminviews.accept,name='accept'),
    path('reject/<int:id>/',adminviews.reject,name='reject'),
    path('booking_status',customerviews.booking_status,name='booking_status'),
    path('work_assign',adminviews.work_assign,name='work_assign'),
    path('view_work',customerviews.view_work,name='view_work'),
    path('status',workmanagerviews.status,name='status'),
    path('update_work/<int:id>/',workmanagerviews.update_work,name='update_work'),
    path('work_status',adminviews.work_status,name='work_status'),
    path('delete_work/<int:id>/', adminviews.delete_work, name='delete_work'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('profile_cstmr',customerviews.profile_cstmr,name='profile_cstmr'),
    path('profile_manager',workmanagerviews.profile_manager,name='profile_manager')
]
